spring.application.name=cookie_based_jwt_auth
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/cookie_based_jwt_auth_DB
#DOCKER LOCAL SETUP
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/cookie_based_jwt_auth_DB
spring.datasource.username=postgres
spring.datasource.password=__YOUR_DB_PASSWORD__


# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Corrected Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.session.jdbc.platform=postgresql

#__KEYS__
#application.security.jwt.secret-key=__YOUR_SECRECT_KEY__ (256-Bit long key is required)
#**__generate secret using bash__**


#__COOKIE_NAME__
#application.security.cookie-name=__YOUR_COOKIE_SECRECT__
