spring.application.name=refresh_token
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/refresh_token_db
#DOCKER LOCAL SETUP
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/refresh_token_db
spring.datasource.username=postgres
spring.datasource.password=__YOUR_DB_PASSWORD__


# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Corrected Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.session.jdbc.platform=postgresql

#__KEYS__
#application.security.jwt.secret-key=__YOUR_SECRET_KEY__(256BIT)

#__COOKIE_NAME__
#application.security.cookie-name=__YOUR_COOKIE_NAME__

#__COOKIE_EXPIRY__
application.security.cookie.access-token-expiry-seconds=900
application.security.cookie.refresh-token-expiry-seconds=604800
application.security.jwt.refresh-token-expiration-ms=604800000


